# Generated by Django 4.1.5 on 2023-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True, default="", help_text="Account Display Name", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
