name: Simple Blog CI

on:
  pull_request:
    branches: [ "master" , "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    env:
      BLOG_SECRET_KEY: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_SIGNING_KEY: ${{ secrets.BLOG_SIGNING_KEY }}
      BLOG_DJANGO_DEBUG: ${{ secrets.BLOG_DJANGO_DEBUG }}
      BLOG_DB_NAME: ${{ secrets.BLOG_DB_NAME }}
      BLOG_USER: ${{ secrets.BLOG_USER }}
      BLOG_PASSWORD: ${{ secrets.BLOG_PASSWORD }}
      BLOG_HOST: ${{ secrets.BLOG_HOST }}
      BLOG_PORT: ${{ secrets.BLOG_PORT }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: black --diff --check $(git ls-files '*.py')
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    - run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Run Tests
      run: |
        python manage.py test
