name: Simple Blog CI

on:
  pull_request:
    branches: [ "master" , "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    env:
      BLOG_SECRET_KEY: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_DJANGO_DEBUG: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_DB_NAME: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_USER: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_PASSWORD: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_HOST: ${{ secrets.BLOG_SECRET_KEY }}
      BLOG_PORT: ${{ secrets.BLOG_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
