name: Simple Blog CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" , "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]
    env:
      BLOG_SECRET_KEY: ${{ secrets.BLOG_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
